services:

    blast_outer_extension.listener.outer_extension:
        class: Blast\OuterExtensionBundle\EventListener\OuterExtensionListener
        tags:
            - { name: doctrine.event_subscriber, event: loadClassMetadata }
        calls:
            - [setLogger, ['@logger']]
            - [setExtendedClasses, ['%kernel.bundles%']]
