services:

    blast_outer_extension.listener.outer_extension:
        class: Blast\OuterExtensionBundle\EventListener\OuterExtensionListenerRR
        tags:
            - { name: doctrine.event_subscriber, event: loadClassMetadata }
        calls:
            - [setLogger, [@logger]]
            - [setExtendedClasses, [%kernel.bundles%]]
