services:

    librinfo_outer_extension.listener.outer_extension:
        class: Librinfo\OuterExtensionBundle\EventListener\OuterExtensionListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger, [@logger]]
            - [setKernelBundles, [%kernel.bundles%]]